name: cookiecutter-dev
channels:
  - defaults
  - conda-forge
dependencies:
  - "cookiecutter>=1.7.2"
  - "pytest>=6.2.2"
  - "black>=20.8b1"
  - "pylint>=2.3.1"
  - "isort>=5.7.0"
  - "pre-commit>=2.10.1"
