name: cookiecutter
channels:
  - defaults
  - conda-forge
dependencies:
  - "pytest>=6.2.2"
  - "black>=19.10b0"
  - "pylint>=2.3.1"
  - "isort>=5.7.0"
  - "pre-commit>=2.10.1"
  - "git-lfs>=2.13.2"
  - "pandas>=1.2.3"
  - "numpy>=1.19.2"
  - "scipy>=1.6.1"
  - "scikit-learn>=0.24.1"
  - "seaborn>=0.11.1"
  - "ipykernel>=5.3.4"
  - "metaflow>=2.2.7"
  - "wandb>=0.10.20"
