channels:
  - defaults
  - conda-forge
dependencies:
  - ipykernel
  - seaborn
  - pandas
  - numpy
  - scikit-learn
  - black
  - scipy
  - pytest
  - isort
  - metaflow
  - wandb
  - git-lfs
  - pre-commit
